# All services defined: 
services: 

  # Service name:
  backend-service: 

    # Container name: 
    container_name: docker-container

    # Restart policy (when to restart if crashed/stoped):
    restart: unless-stopped

    # Image name to build: 
    image: assaffink/hello-backend:1.0

    # Image location: 
    build: .

    # Port binding (host-port:container-port):
    ports: 
      - 3002:3001

    # Environment variables - first way:
    # environment:
    #   - PORT=3001
    #   - CLOUD_SERVICE_PROVIDER=AWS
    #   - CLOUD_SUPPORT_EMAIL=support@aws.com

    # Environment variables - second way:
    environment:
      PORT: 3001
      CLOUD_SERVICE_PROVIDER: AWS
      CLOUD_SUPPORT_EMAIL: support@aws.com

    # start our backend when container started: 
    command: npm start

    