# All services defined: 
services: 

  # Service name:
  backend-service: 

    # Container name: 
    container_name: backend-container

    # Restart policy (when to restart if crashed/stoped):
    restart: unless-stopped

    # Image name to build: 
    image: assaffink/kittens-backend:1.0

    # Image location: 
    build: .

    # Port binding (host-port:container-port):
    ports: 
      - 3002:3001

    # Volumes:
    volumes:

      # Host Volume for error logs (host-path:container-path)
      - C:/ErrorsLog:/app/src/1-assets/logs/errors

      # Anonymous Volume for activities logs
      - /app/src/1-assets/logs/activities

      # Named Volume for json and images
      - my-kittens-json:/app/src/1-assets/json
      - my-kitten-images:/app/src/1-assets/images

    # Environment variables - second way:
    environment:
      PORT: 3001

    # start our backend when container started: 
    command: npm start

# Named Volume List:
volumes:
  my-kittens-json:
  my-kitten-images:

